### ISSUE TITLE
File corruption using this library

### ISSUE THREAD

**Issue by mmindenhall** [alexmojaki/s3-stream-upload#17]
Hi,

I'm working on a data ingestion platform that starts with a REST API that accepts files via `Content-Type:multipart/form-data`, with `Transfer-Encoding:chunked`.  The API is implemented with Micronaut (uses netty internally), and we use the s3-stream-upload library to stream the file chunks to S3.

We're using the following settings:

- numStreams: 1
- numUploadThreads: 2
- queueCapacity: 2
- partSize: 5

Here's the code we're using, with our business logic stripped out.

```kotlin
    @Post("/")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    fun postSet(dataSet: DataSet, dataFile: StreamingFileUpload): HttpResponse<Response> {
        // In the arguments above, dataSet is JSON metadata, and dataFile produces the
        // uploaded chunks of the file

        val s3Client = // the client (actually injected into the controller)
        val bucket = // the bucket name
        val key = // the object key 

        val stm = StreamTransferManager(bucket, objectKey, s3Client)
                .numUploadThreads(2)
                .queueCapacity(2)
                .partSize(5)
        val multiPartOutStr = stm.multiPartOutputStreams[0]

        // wrap in DigestOutputStream to calculate md5sum as chunks are received
        val md5 = MessageDigest.getInstance("MD5")
        val md5OutStr = DigestOutputStream(multiPartOutStr, md5)

        // Process the upload chunks as they arrive
        val upload: Single<Result<Boolean, Throwable>> = Flowable.fromPublisher(dataFile)
                // close and complete the S3 upload after all chunks are received
                .doOnComplete {
                    md5OutStr.close()
                    stm.complete()
                }
                // subscribe to the StreamingFileUpload
                .subscribeOn(Schedulers.io())
                // process each uploaded chunk
                .map<Result<Boolean, Throwable>> { p: PartData ->
                    val inStr = p.inputStream
                    try {
                        // copy data to s3
                        val n = IOUtils.copyLarge(inStr, md5OutStr)
                        Result.Success(true)
                    } finally {
                        inStr.close()
                    }
                }
                // reduce to a single Result (Success or Error)
                .reduce {_, cur -> cur }
                // abort S3 upload, wrap error in Result and return
                .onErrorReturn { t ->
                    stm.abort()
                    Result.Error(t)
                }
                // Convert to Single
                .toSingle()

        // wait for upload to complete
        val uploadResult = upload.blockingGet()
        return when (uploadResult) {
            is Result.Success -> {
                logger.debug { "===== File uploaded" }

                // the md5sum we've been calculating as chunks of the file are received
                val md5sum = DatatypeConverter.printHexBinary(md5.digest()).toLowerCase()
                logger.debug { "===== md5sum of uploaded file: $md5sum" }

                HttpResponse.created(Response.success(dataSet))
            }
            is Result.Error -> {
                logger.error("Upload failed: ", uploadResult.error)
                HttpResponse.badRequest(Response.fail(mapOf("error" to uploadResult.error.message)))
            }
        }
    }
```

In the code above, the md5sum is being calculated by the `DigestOutputStream` that wraps the `MultipartOutputStream`.  When the upload is complete, the md5sum value logged by this code matches the value calculated by the md5sum command line tool, so we are certain that the file is not being corrupted in transit.

However, the file that shows up in S3 is frequently not the same size as the file that was uploaded.  For example, one test file we uploaded is 3,943,327,602 bytes, but the resulting file in S3 is 3,932,837,726.  In this case, the S3 file is smaller than the original, but we've also seen it end up being larger.  We're seeing corrupted/incorrect files more than 50% of the time at this point.

Given that the md5 value is correct, this points to a problem with the s3-stream-upload library, or with Amazon's multipart upload API.

**Comment by alexmojaki** [comment]
Thanks for the report. This is very concerning. I see the difference is almost exactly 10MB, which is probably significant, but I don't have any other clues. Please enable debug logging on the library and send a file with those log, maybe that'll help. Ideally with smaller files (for smaller logs) and cases of being both larger and smaller.

I don't know how this Flowable stuff works. Is it possible that `md5OutStr.close()` gets called before everything has finished writing to it?

**Comment by mmindenhall** [comment]
Tomorrow is my last day at the company, but I'll try to get some logs posted.  We've been testing with this API for a while with files up to ~500MB in size, and never saw this happen.  A new customer will be sending larger files, so we started testing with files 2-5GB in size.  We've only seen this happen with these larger files.  And again, it doesn't happen every time, which leads me to believe there's some sort of race condition.

I just ran with some additional logging and verified that I see logging for each chunk as it is completed within the `map` block, and then after the final chunk I see logging at the start of the `doOnComplete` block.  The log messages in both cases are made by the same thread, so I don't think it's possible that we have a race condition where `doOnComplete` (which invokes `md5OutStr.close()`) is invoked before we finish writing all of the data.

**Comment by mmindenhall** [comment]
One of my colleagues changed the partSize to 10MB, and we haven't seen this error since then.  We have no idea why that would matter, other than perhaps further reducing the chances that a race condition will occur.

**Comment by mmindenhall** [comment]
We changed the partSize back to 5MB and ran again.  We had it succeed once, then fail once.  I extracted the logs from the failed attempt (sorry for being in JSON format...that's what we use inside our kubernetes cluster, as the logs get pushed to Kibana).

File we're uploading:  3,943,327,602 bytes
File uploaded to S3:  3,932,833,670 bytes

File md5sum:  26ec8b023a3ec28459d0bd78e7efec38
Calculated md5sum (as chunks are received...see last line of logging): 26ec8b023a3ec28459d0bd78e7efec38

Thanks!

[data-api-logs-1236.txt](https://github.com/alexmojaki/s3-stream-upload/files/3336307/data-api-logs-1236.txt)

**Comment by claykirk** [comment]
I have some additional information related to this bug if it may be helpful. I tried changing the part size back to 10MB and I'm now seeing that part size fail.  I attached the logs.

File being uploaded: 3943327602
File uploaded to s3: 3932837746

File md5sum: 26ec8b023a3ec28459d0bd78e7efec38
Calculated md5sum (as chunks are received...see last line of logging): 26ec8b023a3ec28459d0bd78e7efec38

Thank you!
[part-size-10MB.txt](https://github.com/alexmojaki/s3-stream-upload/files/3336575/part-size-10MB.txt)

**Comment by alexmojaki** [comment]
Thanks guys.

@claykirk there's half a JSON object missing at the start of the file you attached. Please confirm that it has a message starting "Splitting stream of size ...". It's right before "Putting [Part number 1 containing 10.00 MB] on queue", the first message that appears in the file. That threw me off for a bit.

The logs seem to indicate that everything went fine. I added up all the sizes in bytes and got the final file size. And they all seem to have been uploaded. But the difference between the pairs of sizes you two tell me is always just over 10MB, which is one or two parts, suggesting they somehow didn't make it to S3. Very strange.

Please run something like this (keeping the strings the same) and send me the results:

```java
            PartListing partListing = s3Client.listParts(
                    new ListPartsRequest(
                            "di-data-lake-dev-da6fdeda-9bd0-4f89-9dde-8485ef4b4d1d",
                            "data-source-transaction-5d07f74b2614a10001c113ea/data-set-5d14fb6393ec8e0001af81eb/raw/ANTrans-snappy.avro",
                            "lOXUQef92XX32Hu1EjUsXde3Hc21GPgn130l2MF.du3QMxVyq5B.CsSaBc9Gd1QEqXYB_Dq40nWNllX6h6gUrT7aqnnD1PBxptWjiB9H_c7KESUJv3rrc6Jldcs35Qp5HBU8Tz5AN.jsWTkNm_GhvQ--"));
            for (PartSummary partSummary : partListing.getParts()) {
                System.out.println(partSummary.getPartNumber() + " " + partSummary.getSize());
            }
```

**Comment by alexmojaki** [comment]
Also please try reproducing the bug with `.numUploadThreads(1).queueCapacity(1)`.

**Comment by claykirk** [comment]
Hi Alex, I've attached the full upload log file. My apologies for leaving out the first part of the log message.

I also tried listing the parts for the upload you referenced above but I'm getting a message from AWS saying that the upload has either been aborted or has completed.

"An error occurred (NoSuchUpload) when calling the ListParts operation: The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed."

I tried using the code you provided above and I also used the "aws s3api list-parts" command and they are both reporting that the upload id is invalid, or the upload has been aborted or completed.

[part-size-10MB-complete.txt](https://github.com/alexmojaki/s3-stream-upload/files/3337528/part-size-10MB-complete.txt)

**Comment by alexmojaki** [comment]
Right, I had a feeling that it doesn't work for completed uploads but wasn't sure. We'll have to do it the slightly harder way. Use this subclass to do the upload:

```java
public class MyStreamTransferManager extends StreamTransferManager {

    private static final Logger log = LoggerFactory.getLogger(MyStreamTransferManager.class);

    public MyStreamTransferManager(String bucketName, String putKey, AmazonS3 s3Client) {
        super(bucketName, putKey, s3Client);
    }

    @Override
    public void customiseCompleteRequest(CompleteMultipartUploadRequest request) {
        PartListing partListing = s3Client.listParts(
                new ListPartsRequest(bucketName, putKey, uploadId));
        for (PartSummary partSummary : partListing.getParts()) {
            log.debug(
                    partSummary.getPartNumber()
                            + " " + partSummary.getETag()
                            + " " + partSummary.getSize()
            );
        }
        for (PartETag partETag : request.getPartETags()) {
            log.debug(partETag.getPartNumber()
                    + " " + partETag.getETag()
            );
        }
    }
}
```

Reproduce the bug and send me the full logs again.

**Comment by claykirk** [comment]
Hi Alex, 
Here is the output with MyStreamTransferManager logging...
Clay
[my-stream-tfr-mgr-5MB.txt](https://github.com/alexmojaki/s3-stream-upload/files/3340338/my-stream-tfr-mgr-5MB.txt)

**Comment by claykirk** [comment]
Setting the num threads and queue capacity to 1 seemed to help for the most recent 5MB upload. I've attached the logs for that upload as well.
[threads-1-capacity-1-5MB.txt](https://github.com/alexmojaki/s3-stream-upload/files/3340358/threads-1-capacity-1-5MB.txt)

**Comment by alexmojaki** [comment]
OK, I think I've got it. The list of part etags wasn't thread safe so if two threads tried to add one at the same time things went wrong. Can only happen with multiple threads and is more likely with many parts, meaning big files and small parts.

Upgrade to 2.0.2 and see if it happens again. Test it real hard.

The fact that S3 makes you provide a list of part etags, doesn't warn you when that list is incomplete, and silently leaves parts out, seems like a very dangerous API. I had always assumed the list was for verification and the upload would fail if it didn't match the list S3 stored.

**Comment by claykirk** [comment]
Version 2.0.2 seems to be working without any errors. I changed the threads and capacity back to 2 and I've done a few uploads with 10MB and 5MB part sizes and I haven't seen any issues. I will let you know if I encounter any problems. I appreciate your time and immediate response. Thank you!

Clay

**Comment by alexmojaki** [comment]
Thank you both for the amount of time you spent on this bug report!
