### ISSUE TITLE
Upload thrashing when splitting stream 

### ISSUE THREAD

**Issue by claykirk** [alexmojaki/s3-stream-upload#18]
I'm seeing an issue in the middle of a file upload that is causing some thrashing of the upload process. I'm using a multipart stream manager with 2 queues, 2 threads, and 10MB part size.  The code is the same as what was put into this issue here: https://github.com/alexmojaki/s3-stream-upload/issues/17. 

I can send some logs as well.

**Comment by alexmojaki** [comment]
What do you mean by thrashing?

**Comment by claykirk** [comment]
[stream-thrashing.txt](https://github.com/alexmojaki/s3-stream-upload/files/3444397/stream-thrashing.txt)

**Comment by claykirk** [comment]
> What do you mean by thrashing?

The stream seems to not progress due to the stream splitting. I believe the stream splitting is preventing the upload to complete in a timely manner.

**Comment by alexmojaki** [comment]
I don't know when I'll have time to look at this. In the meantime please describe the problem in more detail. Some stream splitting is conceptually a necessary part of the library to upload multiple parts and not hold everything in memory. You can reduce the number of times it splits by increasing the part size. You also might be able to upload faster if you use more threads. Does that help?

**Comment by claykirk** [comment]
Yes. 

I will investigate further and see if I can resolve or get some more detail on why this happens so often.

Thanks!

**Comment by bwang221** [comment]
I can confirm this, if you set number of streams > 1, with a large file (i used 2 GB), it hangs forever.

**Comment by alexmojaki** [comment]
This is likely related to #27. I've released a fix in 2.2.1, upgrade once it becomes available and let me know if it's still a problem.
