### ISSUE TITLE
README in sync with Releases

### ISSUE THREAD

**Issue by StephanPraetsch** [alexmojaki/s3-stream-upload#20]
Hi,

I really like a mentioned maven dependency in README but please keep it up to date. Currently README says 2.0.0 but there is 2.0.3 already published (https://mvnrepository.com/artifact/com.github.alexmojaki/s3-stream-upload).

Will you please update the README to the latest release?

**Comment by alexmojaki** [comment]
Thanks for pointing this out. I think it's better that I don't try to keep it up to date manually. Besides the website has code for other tools which are newer than maven.
