### ISSUE TITLE
Support empty stream upload

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/s3-stream-upload#21]

**Comment by alexmojaki** [comment]
Now supported in version 2.1.0.

**Comment by nditur** [comment]
Thanks a lot for the quick implementation!
BTW, I'm using aws-java-sdk-s3 version 1.11.401 which is older then yours. Do you see any problem with that?

**Comment by alexmojaki** [comment]
I don't know of any problem. See https://github.com/alexmojaki/s3-stream-upload/pull/19 where I was advised to keep it up to date. If you're able to use an older version along with this library, that's fine.

**Comment by nditur** [comment]
Thanks!
