### ISSUE TITLE
Set Content-disposition

### ISSUE THREAD

**Issue by gabhishekprdxn** [alexmojaki/s3-stream-upload#22]
Hi, Thanks for this lib. 
I'm using this lib. I need help about set Content-disposition. 
Can you guide me on how to achieve this? here is my sample code.

```java
String pptxFileName = pptDestination + tempPresentation.getSlides().get_Item(0).getLayoutSlide().getName().replaceAll(" ", "") + ".pptx";
		try {			
			streamTransferManager = new StreamTransferManager(MAIN_ASSET_BUCKET,pptxFileName, s3Client); // Upload data to S3 in Chunks.
			multipartOutputStream = streamTransferManager.getMultiPartOutputStreams().get(0);
			tempPresentation.save(multipartOutputStream, SaveFormat.Pptx);
		} finally {
			if(!multipartOutputStream.equals(null) && !streamTransferManager.equals(null)) {
				multipartOutputStream.close();
				streamTransferManager.complete();               
			}
		}
```

**Comment by gabhishekprdxn** [comment]
Its really urgent requirement for me. @alexmojaki could you guide me?

**Comment by alexmojaki** [comment]
I said in #11 that I didn't think this library was helpful to you as `.save()` just writes the whole thing in one go. Did you understand that?

Anyway the solution is to subclass `StreamTransferManager` and override one of the `customise*Request` methods to set the content disposition: http://alexmojaki.github.io/s3-stream-upload/javadoc/apidocs/alex/mojaki/s3upload/StreamTransferManager.html#customiseCompleteRequest-com.amazonaws.services.s3.model.CompleteMultipartUploadRequest-

**Comment by alexmojaki** [comment]
Something like this:

```java
    public void customiseInitiateRequest(InitiateMultipartUploadRequest request) {
        request.getObjectMetadata().setContentDisposition("...");
    }
```

**Comment by gabhishekprdxn** [comment]
Thanks! @alexmojaki. it's working for me.
