### ISSUE TITLE
Random nullpointer exception

### ISSUE THREAD

**Issue by fredwilliamson** [alexmojaki/s3-stream-upload#29]
Hi,
We used your API in version 2.1.0 to upload a document in S3 without having the size of the file. It worked on 95% of upload but for some of them we have the following error:

 

java.lang.NullPointerException: null
    at alex.mojaki.s3upload.StreamTransferManager.complete(StreamTransferManager.java:322)
    at XXXXX.S3Adapter.createDocument(S3Adapter.java:103)
    
We don't find any relation between cases where it failed or not. This is the implemantation we did with your API

 

    public Document createDocument(Document document , InputStream stream) throws DocumentManagementException {
        StreamTransferManager manager = new StreamTransferManager(this.bucketname, getKey(document.getDocumentRef()), this.s3client){
            @Override
            public void customiseInitiateRequest(InitiateMultipartUploadRequest request) {
                super.customiseInitiateRequest(request);
                ObjectMetadata metadata = new ObjectMetadata();
                metadata.addUserMetadata("d_doc_extension" , "." + FilenameUtils.getExtension(document.getDocumentName()));
                metadata.addUserMetadata("d_doc_name" , document.getDocumentRef());
                request.setObjectMetadata(metadata);
            }
        }.partSize(30);

 

        try (MultiPartOutputStream os = manager.getMultiPartOutputStreams().get(0)) {
            IOUtils.copy(stream, os);
            stream.close();
        } catch (IOException e) {
            e.printStackTrace();
            throw new DocumentManagementException(e.getMessage());
        } finally {
            manager.complete();
        }

 

        ObjectMetadata meta =  this.getDocumentMetadata(document.getDocumentRef());
        document.setFileSize(meta.getContentLength());
        return document;
    }
    
Can you help us to find the issue ?

 

Regards

**Comment by alexmojaki** [comment]
Hi, sorry this slipped my mind, but have you tried upgrading to the latest version 2.2.1?

**Comment by alexmojaki** [comment]
Closing until this gets confirmed again.
