### ISSUE TITLE
Content-type always sent as application/x-www-form-urlencoded; charset=utf-8

### ISSUE THREAD

**Issue by MaikeMota** [alexmojaki/s3-stream-upload#3]
I'm using the _StreamTransferManager_ to do the upload the files to my Bucket, but all the files uploaded are saved with the **Content-Type : application/x-www-form-urlencoded; charset=utf-8**.

There is any way to prevent that, or just manually set the **Content-Type** for the file while uploading? I hope that I can upload  the files and set the **Content-Type** _like the original file_.

**Comment by MaikeMota** [comment]
We made an wrapper for the StreamTransferManager using the decorator pattern like that, and the problem is gone:
```
public class MediaTypedStreamTransferManager {
		
	private StreamTransferManager manager;

	public MediaTypedStreamTransferManager(String bucketName, String putKey, AmazonS3 s3Client, int numStreams,
			int numUploadThreads, int queueCapacity, int partSize, MediaType mediaType) {
		
		manager = new StreamTransferManager(bucketName, putKey, s3Client, numStreams, numUploadThreads, queueCapacity, partSize){
			@Override
			public void customiseInitiateRequest(InitiateMultipartUploadRequest request) {
				super.customiseInitiateRequest(request);
				ObjectMetadata metadata = new ObjectMetadata();
				metadata.setContentType(mediaType.toString()); // set the ContentType for the object that will be uploaded
				request.setObjectMetadata(metadata);
			}
		};	
	}
	
	public void complete() {
		manager.complete();
	}
	
    public List<MultiPartOutputStream> getMultiPartOutputStreams() {
        return manager.getMultiPartOutputStreams();
    }
	
};	
```

**Comment by alexmojaki** [comment]
Sorry I didn't see this, I somehow missed notifications from this repo.

This is exactly the kind of thing methods like `customiseInitiateRequest` are for. I'm not sure why you made a wrapper class, the inheritance looks sufficient.

**Comment by MaikeMota** [comment]
When i opened this issue, i could not figure out how to change  the `ObjectMetadata`, but later, getting in deep on the source code i saw the `customiseInitiateRequest` method.

The inheritance maybe would have been sufficient, but in our case was preferred to use this pattern to add the wanted behavior.

**Comment by alexmojaki** [comment]
Sorry, it's mentioned at the end of the docs linked from the README (http://alexmojaki.github.io/s3-stream-upload/javadoc/apidocs/alex/mojaki/s3upload/StreamTransferManager.html), do you think it's too inconspicuous?

**Comment by MaikeMota** [comment]
I read this documentation and it have provided me valuable information about the use of your library, i also saw the mention about the `customize*Request`.

Everything was going fine until i embeded the uploaded files on a webpage or try to downloading it directly from AWS S3, they was delivered as RAW file and browser does not recognized the type of it. After some google research and reading your code i figure out that Content-Type never was set and **AWS S3** set this as `application/x-www-form-urlencoded; charset=utf-8`.

After that, i just changed the Metadata on **AWS S3** and the files worked as expected. Then i wrote the decorator to do this job before upload the file and everything is working fine until now.

Maybe i have missed something, but i think that for default the library should sent the Content-Type as the same type as the original file to prevent this kind of issue.

Anyway, thanks for your attention.

**Comment by alexmojaki** [comment]
> Maybe i have missed something, but i think that for default the library should sent the Content-Type as the same type as the original file to prevent this kind of issue.

How? The library has no concept of the original file.

**Comment by andrewgaul** [comment]
If you wonder why the Content-Type is `application/x-www-form-urlencoded; charset=utf-8` and not something more sensible like `application/octet-stream`, see aws/aws-sdk-java#545.  Upgrading the SDK addresses this.  This does not address the configuration issue but the newer default works better with various clients.
