### ISSUE TITLE
Java heap space issue

### ISSUE THREAD

**Issue by swetabdas** [alexmojaki/s3-stream-upload#32]
Hi,
Thank you for sharing the library code. Its really helpful. 

I just have one issue with this. When I am trying to upload files with part size of 100MB or more. I am getting a Java heap space error. I am not sure what is causing the issue.

```java
public void uploadObject(InputStream inputStream) {
		String encryptionType = this.s3Encryption.getEncryptionType();
		StreamTransferManager manager = new StreamTransferManager(this.bucketName, this.key, this.s3Client).numStreams(1).numUploadThreads(1).queueCapacity(2)
						.partSize(this.s3Connection.getPartSize());
		try (MultipartOutputStream outputStream = manager.getMultiPartOutputStreams().get(0)) {
			StreamUtil.copy(inputStream, outputStream);
		} catch (Exception e) {
			manager.abort();
			throw new Exception (MULTIPART_OPERATION_FAILED, e);
		} finally {
			manager.complete();
		}
	}
```

Can you suggest, what I am doing wrong here?

**Comment by alexmojaki** [comment]
I don't know. In the worst case scenario there should be 106 MB in the stream, 200 MB in the queue, and 100 MB in the upload thread. If that's too much then decrease the queue capacity and maybe the part size. The part size only needs to be 100 MB if you expect the files might have a total size of up to 1 TB. If it seems to be using more memory than that, use a memory profiling tool and let's see what it says.

**Comment by swetabdas** [comment]
I have analyzed the heap dump and found that the maximum memory is being used for byte[]. In the Convertible Output stream byte[] is being used.

**Comment by alexmojaki** [comment]
Right, that makes sense. How much is in those arrays? Is it much more than 400 MB? Can you share some screenshots or something?

**Comment by swetabdas** [comment]
Yes, and my input file size was 6GB. Attached are the screenshot and the stack trace of the thread. I was trying to find an alternate of converting Inputstream to ByteArrayStream in ConvertibleOutputStream class but I was not successful.
![heapDump](https://user-images.githubusercontent.com/73473478/98483072-a1e4da00-222b-11eb-928c-06d0cb1fa547.jpg)
[heap_dump_stacktrace.txt](https://github.com/alexmojaki/s3-stream-upload/files/5507082/heap_dump_stacktrace.txt)

**Comment by alexmojaki** [comment]
That's the 106 MB I mentioned earlier for the stream. You specified a part size of 100 MB, so this is normal. 

If your file is less than 50 GB, then the minimum part size of 5 MB is fine.

**Comment by swetabdas** [comment]
Thanks for a quick reply. But as it converting from Steam to ByteArrayOutputStream, my client is not accepting it. Therefore, I am trying to use Re-settable Input stream, but I am not able to achieve it. Can you provide me any help here? I am not sure I should ask this question. But I am just trying to find a solution.

**Comment by alexmojaki** [comment]
I have no idea what you're saying.

**Comment by swetabdas** [comment]
No problem @alexmojaki, I understand. Its my bad, I was not able to give details . 
Thank you so much for help.  The library code was also really helpful. 

The issue I am facing is in my client environment. I have to change the code as per their environment. 

Thank you.
