### ISSUE TITLE
InvalidPartOrder error on complete

### ISSUE THREAD

**Issue by dana-katzenelson-livongo** [alexmojaki/s3-stream-upload#33]
I get the following error when using this API with smaller strings written:

```
Aborting [Manager uploading to $LOCATION with id $ID] due to error: com.amazonaws.services.s3.model.AmazonS3Exception: The list of parts was not in ascending order. Parts must be ordered by part number. (Service: Amazon S3; Status Code: 400; Error Code: InvalidPartOrder; Request ID: $REQ_ID; S3 Extended Request ID: $EXT_REQ_ID; Proxy: null), S3 Extended Request ID: $EXT_REQ_ID
```

According to Amazon Documentation (https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/MS3CompleteMultipartUploadCompleteMultipartUploadRequest.html)
>  Error code: InvalidPartOrder
>
>    Description: The list of parts was not in ascending order. The parts list must be specified in order by part number.
>
>    400 Bad Request 
    
Can you maybe sort `StreamTransferManager.partETags` by `PartETag.partNumber` before passing it into `CompleteMultipartUploadRequest()`?

**Comment by alexmojaki** [comment]
Hi, thanks for the error report!

I've never seen this error before, I wonder if it's a new requirement from AWS?

This should be easy to solve. Here is all the relevant code:

https://github.com/alexmojaki/s3-stream-upload/blob/9dff468c61b7911204e88e98612e7d1cb9b3b8aa/src/main/java/alex/mojaki/s3upload/StreamTransferManager.java#L381-L404

Particularly important are lines 386, 390, and 404. The parts are already sorted for a different reason, we can just rearrange that.

Could you make a PR?

**Comment by dana-katzenelson-livongo** [comment]
I made one at https://github.com/alexmojaki/s3-stream-upload/pull/34 before seeing this

**Comment by dana-katzenelson-livongo** [comment]
Updated
