### ISSUE TITLE
Can I stream a file upload to S3 from Rest API (MultipartFile file) without Storing in Memory by using this library?

### ISSUE THREAD

**Issue by fusekamal** [alexmojaki/s3-stream-upload#39]
Do we have an example to demonstrate how to upload from REST endpoint to s3 bucket, end to end an example? 

for instance: Rest API
 @PostMapping(value = "/upload")
public String uploadFile(MultipartFile file) {
// Streaming code to s3 bucket goes here
}

**Comment by alexmojaki** [comment]
I don't know how MultipartFile. Basically you need to iteratively read chunks of data from your input stream/source/file and write those chunks to a MultiPartOutputStream from this library. See #13 and #30 for similar discussions.

**Comment by fusekamal** [comment]
Thank you @alexmojaki :)
