### ISSUE TITLE
compressing input data before sending to s3

### ISSUE THREAD

**Issue by SanthoshPrasad** [alexmojaki/s3-stream-upload#5]
Hi @alexmojaki, can it be extended to support input compression as well?, i created a gzip wrapper over byte array output stream, but it's failing with multiple parts even though it's working with single part.

**Comment by alexmojaki** [comment]
I don't know, you'd have to show me your code. I imagine it wouldn't work with multiple threads, but multiple parts probably shouldn't be a problem.
